### ISSUE TITLE
Using .eslint for JavaScript linting

### ISSUE THREAD

**Issue by weiland** [bitcrowd/frontend#4]
I would recommend adding a eslint file as well since it has a better environment for styles and presets for angular and react.

**Comment by pmeinhardt** [comment]
Hey @weiland. How about going through and updating the sections on JS and linting. We should probably aim for a standard bitcrowd `.eslintrc`, maybe even an `eslint-config-bitcrowd` npm package (probably based off of `eslint-config-airbnb`)?

**Comment by weiland** [comment]
I'm totally in for the `eslint-config-bitcrowd` package.

**Comment by pmeinhardt** [comment]
Nice. Do you want to go ahead and create a repo (+ package) or should we get together maybe later today?

**Comment by pmeinhardt** [comment]
Quick checklist:

- [ ] create repo or rather use `linting/js` subdirectory of this repo? (I think I'd go for the latter)
- [ ] set up an npm bitcrowd account (check with @bitboxer and @xhr15 which email to use etc. – maybe they keep a list of official bitcrowd accounts)
- [ ] create npm package `eslint-config-bitcrowd`
  - [ ] based on specific version of `eslint-config-airbnb`
  - [ ] go through rules and override where appropriate after discussing
- [ ] ES5 version?
